version: '3.7'

services:

  streamlit:
    container_name: streamlit
    env_file:
      - .env
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
        - 8001:8001
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [compute, utility]